//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBetCore.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Applicationstring {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Applicationstring() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickBetCore.Resource.Applicationstring", typeof(Applicationstring).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your account is blocked .please contact the administrator.
        /// </summary>
        public static string Accountblocked {
            get {
                return ResourceManager.GetString("Accountblocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a Customer with the same information, try to search via email or phone in your customer list..
        /// </summary>
        public static string Alreadyhavecustomer {
            get {
                return ResourceManager.GetString("Alreadyhavecustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount transferred successfully.
        /// </summary>
        public static string Amounttransferredsuccessfully {
            get {
                return ResourceManager.GetString("Amounttransferredsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot transfer Funds to yourself..
        /// </summary>
        public static string CannotTransferFunds {
            get {
                return ResourceManager.GetString("CannotTransferFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match the confirm password.
        /// </summary>
        public static string CompareMessageIfPasswordMatch {
            get {
                return ResourceManager.GetString("CompareMessageIfPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer created successfully.
        /// </summary>
        public static string Customercreatedsuccessfully {
            get {
                return ResourceManager.GetString("Customercreatedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address not recognised.
        /// </summary>
        public static string Emailaddressnotrecognised {
            get {
                return ResourceManager.GetString("Emailaddressnotrecognised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry we are not able take your request right now ,please try again later!.
        /// </summary>
        public static string Fundnottransferingerror {
            get {
                return ResourceManager.GetString("Fundnottransferingerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient balance to perform this transaction.
        /// </summary>
        public static string Insufficientbalance {
            get {
                return ResourceManager.GetString("Insufficientbalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient balance .
        /// </summary>
        public static string InsufficientbalanceInWallet {
            get {
                return ResourceManager.GetString("InsufficientbalanceInWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Model.
        /// </summary>
        public static string InvalidModel {
            get {
                return ResourceManager.GetString("InvalidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you entered doesn&apos;t match the password the system expects for the account you&apos;re attempting to access.
        /// </summary>
        public static string InvalidPasword {
            get {
                return ResourceManager.GetString("InvalidPasword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Refer Code.
        /// </summary>
        public static string InvalidReferCode {
            get {
                return ResourceManager.GetString("InvalidReferCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid username or password.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment completed successfully.
        /// </summary>
        public static string Paymentcompletedsuccessfully {
            get {
                return ResourceManager.GetString("Paymentcompletedsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you don&apos;t have permission to access.
        /// </summary>
        public static string permissiontoaccess {
            get {
                return ResourceManager.GetString("permissiontoaccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist ,please check again email or Phone.
        /// </summary>
        public static string PlayerNotFound {
            get {
                return ResourceManager.GetString("PlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid amount!.
        /// </summary>
        public static string Pleaseentervalidamount {
            get {
                return ResourceManager.GetString("Pleaseentervalidamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for registering with QuickbetNG.Please open your email to verify the account..
        /// </summary>
        public static string RegistrationMail {
            get {
                return ResourceManager.GetString("RegistrationMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request canceled successfully.
        /// </summary>
        public static string Requestcanceledsuccessfully {
            get {
                return ResourceManager.GetString("Requestcanceledsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required.
        /// </summary>
        public static string RequiredFiled {
            get {
                return ResourceManager.GetString("RequiredFiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved.
        /// </summary>
        public static string Resolved {
            get {
                return ResourceManager.GetString("Resolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong please try again.
        /// </summary>
        public static string somethingwentwrong {
            get {
                return ResourceManager.GetString("somethingwentwrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field is required.
        /// </summary>
        public static string StringLengthMessageFullName {
            get {
                return ResourceManager.GetString("StringLengthMessageFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password at least 6 characters.
        /// </summary>
        public static string StringLengthMessagePassword {
            get {
                return ResourceManager.GetString("StringLengthMessagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address you have entered is already registered.
        /// </summary>
        public static string StringUserExistEmailMesssage {
            get {
                return ResourceManager.GetString("StringUserExistEmailMesssage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone you have entered is already registered.
        /// </summary>
        public static string StringUserExistPhoneMesssage {
            get {
                return ResourceManager.GetString("StringUserExistPhoneMesssage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated.
        /// </summary>
        public static string Successfullyupdated {
            get {
                return ResourceManager.GetString("Successfullyupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid email address.
        /// </summary>
        public static string ValidMessageEmailAddress {
            get {
                return ResourceManager.GetString("ValidMessageEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked. please contact support for more information.
        /// </summary>
        public static string Youraccountislocked {
            get {
                return ResourceManager.GetString("Youraccountislocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email verification is pending.
        /// </summary>
        public static string Youremailverificationispending {
            get {
                return ResourceManager.GetString("Youremailverificationispending", resourceCulture);
            }
        }
    }
}
